# Generated by Django 5.1.6 on 2025-02-24 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_visibility_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends Only'), ('PRIVATE', 'Private'), ('DRAFT', 'Draft'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=10),
        ),
    ]
