# Generated by Django 5.1.6 on 2025-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notif_delete_notifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='friends',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
