# Generated by Django 5.1.5 on 2025-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_node_description_node_last_connected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
