# Generated by Django 5.1.6 on 2025-03-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_following_friends'),
        ('myapp', '0009_post_updated'),
    ]

    operations = [
    ]
