# Generated by Django 5.1.6 on 2025-03-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_0009_following_friends_0009_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_node',
            field=models.CharField(blank=True, help_text='Identifier or URL of the node where this user is registered', max_length=255, null=True),
        ),
    ]
