# Generated by Django 5.1.6 on 2025-03-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_home_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark')], default='text/markdown', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='local_copy',
            field=models.BooleanField(default=True, help_text='Is this post native to this node?'),
        ),
        migrations.AddField(
            model_name='post',
            name='needs_sync',
            field=models.BooleanField(default=False, help_text='Track if changes need to be synced'),
        ),
        migrations.AddField(
            model_name='post',
            name='original_node',
            field=models.CharField(blank=True, help_text='Which node created this post', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_nodes_sent',
            field=models.JSONField(blank=True, default=list, help_text='List of node identifiers this post has been sent to'),
        ),
        migrations.CreateModel(
            name='RemoteFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_username', models.CharField(max_length=255)),
                ('remote_node', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('local_user', 'remote_username', 'remote_node')},
            },
        ),
    ]
